<?php

$_code = $block->getMethodCode();
$PaymentGatewayScope = \Magento\Framework\App\ObjectManager::getInstance()->get('\Magento\Framework\App\Config\ScopeConfigInterface');
echo "phtml";
if ($PaymentGatewayScope->getValue('payment/PaymentGateway/fullscreen')) {
    echo '<ul class="form-list" id="payment_form_' . $_code . '" style="display:none;">' .
        '<li>You will be transfered to <a href="https://www.qfpay.com" target="_blank">PaymentGateway</a> to complete your purchase when using this payment method.</li>' .
        '</ul>';
}

